config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :projects
  get 'index' => 'welcome#index'
  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
    friendly_id :title, use: :slugged
    WillPaginate.per_page = 3
end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
    friendly_id :title, use: :slugged
    WillPaginate.per_page = 3
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	def index
		@posts= Post.all.order("created_at desc").paginate(page: params[:page])
	end
	def new
		@post=Post.new
	end
	def create
		@post=Post.create(post_params)
		if @post.save
			redirect_to @post, notice: "yea!, you create it."
		else
			render 'new', notice: "No, You failed us!" 
		end
	end
	def show
		
	end
	def edit
		
	end
	def update
		if @post.update post_params
			redirect_to @post, notice: "wah!, You article is updated!"
		else
			render 'edit', notice: "cant updated, somethings wrong"
		end
	end
	def destroy
		@post.destroy
		redirect_to posts_path
	end



	private
	def post_params
		params.require(:post).permit(:title,:content, :slug)
	end
	def find_post
		@post=Post.friendly.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :update, :edit,:destroy]
	def index
		@projects= Project.all.order("created_at desc").paginate(page: params[:page])
	end
	def new
		@project= Project.new
	end
	def create
		@project= Project.create(project_params)
		if @project.save
			redirect_to @project, notice: "yea!, you create it."
		else
			render 'new', notice: "No, You failed us!" 
		end
	end
	def show
		
	end
	def edit
		
	end
	def update
		if @project.update project_params
			redirect_to @project, notice: "wah!, You project is updated!"
		else
			render 'edit', notice: "cant updated, somethings wrong"
		end
	end
	def destroy
		@project.destroy
		redirect_to projects_path
	end

	private
	def project_params
		params.require(:project).permit(:title,:description,:link, :slug)
	end
	def find_project
		@project= Project.friendly.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts=Post.all.limit(3).order("created_at desc")
		@projects=Project.all.limit(3).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(content)
		renderer= Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
		options={
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Octa Blog</title>
	<link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header id="main-navigation" class="clearfix">
    <%= link_to "Octa Blog", root_url, class: 'name' %>
		
		<nav>
			<%= link_to "Articles", posts_path %>
      <%= link_to "Projects", projects_path %>
			<a href="#">Contact</a>
		</nav>
    </header>

<%= yield %>
<div>
  

<footer id="main-footer">
        <p class="copyright">&copy;2016 Octa Solutions</p>
        <nav>
            <a href="http://facebook.com/" target="_blank"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
        </nav>
    </footer>
    </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<h2><%= pluralize(@post.errors.count,"error") %> prevented this post from saving:</h2>
<ul>
<% @post.errors.full_messages.each do |m| %>
<li><%= m %></li>
<% end %>
</ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>
<br>
<%= f.label :content,"Write your article here" %><br>
<%= f.text_area :content %>
<br>
<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1 id="page-title">Stuff i've written</h1>
    <div id="posts-wrapper" class="skinny-wrapper">
    	<% @posts.each do |post| %>
        <div class="post">
            <p class="date"><%= post.created_at.strftime("%A, %B %d") %></p>
            <h2><%= link_to post.title, post %></h2>
            <hr>
        </div>
        <% end %>
        <%= will_paginate %>
    </div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post-show-content" class="skinny-wrapper wrapper-padding">
        <header>
            <p class="date"><%= @post.created_at.strftime("%A, %B %d") %></p>
            <h1><%= @post.title %></h1>
            <hr>
        </header>
        <div id="content">
            <%= markdown(@post.content) %>
        </div>
        <hr>
        <div id="share-box">
            <p>Share the <%= @post.title %></p>
            <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @saqibroy - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
            <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
        </div>
        <div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/

var disqus_config = function () {
this.page.url = '<%= url_for([@post,{only_path: false}]) %>'; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
this.page.shortname= 'octablog'
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//octablog.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

    <script id="dsq-count-scr" src="//octablog.disqus.com/count.js" async></script>
        <hr>
    </div>
    <%= link_to "Edit", edit_post_path(@post) %>
    <%= link_to "Delete", post_path(@post), method: :delete %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<% if @project.errors.any? %>
<h2><%= pluralize(@project.errors.count,"error") %> prevented this project from saving:</h2>
<ul>
<% @project.errors.full_messages.each do |m| %>
<li><%= m %></li>
<% end %>
</ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>
<br>
<%= f.label :description %><br>
<%= f.text_area :description %>
<br>
<%= f.label :link %><br>
<%= f.text_field :link %>
<br>

<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<div class="skinny-wrapper wrapper-padding">
	<h1>Edit Project</h1>
<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page-title">Stuff i've built</h1>
    <div id="posts-wrapper" class="skinny-wrapper">
    	<% @projects.each do |project| %>
        <div class="post">
            <p class="date"><%= project.created_at.strftime("%A, %B %d") %></p>
            <h2><%= link_to project.title, project %></h2>
            <hr>
        </div>
        <% end %>
        <%= will_paginate %>
    </div>

app/views/projects/new.html.erb
<div class="skinny-wrapper wrapper-padding">
	<h1>New Project</h1>
<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post-show-content" class="skinny-wrapper wrapper-padding">
        <header>
            <p class="date"><%= @project.created_at.strftime("%A, %B %d") %></p>
            <h1><%= @project.title %></h1>
            <hr>
        </header>
        <div id="content">
            <%= markdown(@project.description) %>
            <div class="button-wrapper">
            	<a href="<%= @project.link %>" class="project-button" target="_blank">Visit <%= @project.title %></a>
            </div> 
        </div>
        <hr>
    </div>
    <%= link_to "Edit", edit_project_path(@project) %>
    <%= link_to "Delete", project_path(@project), method: :delete %>

app/views/welcome/index.html.erb
<div class="wrapper wrapper-padding clearfix">
    	<div class="col-1 about homepage-content">
    		<h2>About</h2>
    		<hr>
    		<p>The Google Fonts API will generate the necessary browser-specific CSS to use the fonts.</p>
    		<p> All you need to do is add the font name to your CSS styles.</p>
    	</div>
    	<div class="col-2 homepage-content">

    		<h2>Stuff i've Written</h2>
    		<hr>
            <% @posts.each do |p| %>
            <h3><%= link_to p.title, p %></h3>
            <p class="date"><%= p.created_at.strftime("%A, %b %d") %></p>
            <% end %>
    	</div>
    	<div class="col-3 homepage-content">
            <h2>Stuff i've built</h2>
            <hr>
            <% @projects.each do |p| %>
            <h3><%= link_to p.title, p %></h3>
            <p class="date"><%= p.created_at.strftime("%A, %b %d") %></p>
            <% end %>
            
    	</div>
    </div>
    